<?php

namespace App\Services;

use Illuminate\Support\Str;

class AjudaService
{
    public function categorias(): array
    {
        return [
            [
                'slug' => 'primeiros-passos',
                'titulo' => 'Primeiros Passos',
                'descricao' => 'Configure sua empresa antes de emitir documentos fiscais',
                'icone' => 'fas fa-play',
                'cor' => 'bg-primary-soft',
            ],
            [
                'slug' => 'clientes',
                'titulo' => 'Clientes',
                'descricao' => 'Cadastro de quem vai receber suas notas e cupons',
                'icone' => 'fas fa-user',
                'cor' => 'bg-info-soft',
            ],
            [
                'slug' => 'produtos-estoque',
                'titulo' => 'Produtos e Estoque',
                'descricao' => 'Cadastro de produtos e controle de níveis de estoque',
                'icone' => 'fas fa-box-open',
                'cor' => 'bg-warning-soft',
            ],
            [
                'slug' => 'nfe',
                'titulo' => 'NFe',
                'descricao' => 'Emissão de nota fiscal eletrônica',
                'icone' => 'far fa-file-alt',
                'cor' => 'bg-success-soft',
            ],
            [
                'slug' => 'pdv-nfce',
                'titulo' => 'PDV / NFCe',
                'descricao' => 'Cupom fiscal para vendas de balcão',
                'icone' => 'fas fa-cash-register',
                'cor' => 'bg-danger-soft',
            ],
            [
                'slug' => 'mdfe',
                'titulo' => 'MDFe',
                'descricao' => 'Manifesto eletrônico de documentos fiscais',
                'icone' => 'fas fa-truck',
                'cor' => 'bg-primary-soft',
            ],
            [
                'slug' => 'financeiro',
                'titulo' => 'Financeiro',
                'descricao' => 'Fluxo de caixa, DRE e faturas da assinatura',
                'icone' => 'fas fa-wallet',
                'cor' => 'bg-info-soft',
            ],
            [
                'slug' => 'rejeicoes-sefaz',
                'titulo' => 'Códigos de Rejeição SEFAZ',
                'descricao' => 'O que significa e como resolver cada rejeição de NFe/NFCe',
                'icone' => 'fas fa-exclamation-triangle',
                'cor' => 'bg-danger-soft',
            ],
        ];
    }

    public function categoriaPorSlug(string $slug): ?array
    {
        foreach ($this->categorias() as $categoria) {
            if ($categoria['slug'] === $slug) {
                return $categoria;
            }
        }

        return null;
    }

    public function artigos(): array
    {
        return array_merge($this->artigosGerais(), $this->artigosRejeicoesSefaz());
    }

    public function artigosPorCategoria(string $categoriaSlug): array
    {
        return array_values(array_filter($this->artigos(), function ($artigo) use ($categoriaSlug) {
            return $artigo['categoria'] === $categoriaSlug;
        }));
    }

    public function artigoPorSlug(string $slug): ?array
    {
        foreach ($this->artigos() as $artigo) {
            if ($artigo['slug'] === $slug) {
                return $artigo;
            }
        }

        return null;
    }

    public function buscar(string $termo): array
    {
        $termo = $this->normalizar($termo);

        if ($termo === '') {
            return [];
        }

        return array_values(array_filter($this->artigos(), function ($artigo) use ($termo) {
            $textoBusca = $this->normalizar($artigo['titulo'].' '.$artigo['resumo'].' '.($artigo['palavras_chave'] ?? ''));

            return str_contains($textoBusca, $termo);
        }));
    }

    /**
     * Remove acentos, pontuação e caixa alta para permitir buscas como
     * "certificado" encontrar "Certificado Digital (.pfx)" ou "nao" encontrar "não".
     */
    private function normalizar(string $texto): string
    {
        $texto = Str::ascii($texto);
        $texto = mb_strtolower($texto);
        $texto = preg_replace('/[^a-z0-9]+/', ' ', $texto);

        return trim($texto);
    }

    public function artigosPopulares(): array
    {
        $slugs = ['primeiros-passos', 'emitir-nfe', 'rejeicao-204', 'rejeicao-539', 'produtos-estoque'];

        return array_values(array_filter(array_map(fn ($slug) => $this->artigoPorSlug($slug), $slugs)));
    }

    private function artigosGerais(): array
    {
        return [
            [
                'slug' => 'primeiros-passos',
                'categoria' => 'primeiros-passos',
                'titulo' => 'Primeiros passos no sistema',
                'resumo' => 'Configure a sua empresa antes de emitir documentos fiscais.',
                'palavras_chave' => 'empresa certificado digital pfx senha configuracoes usuarios formas de pagamento cadastro inicial',
                'blocos' => [
                    ['paragrafo' => 'Antes de emitir a primeira nota, é preciso deixar o cadastro da sua empresa completo. São só alguns passos.'],
                    ['heading' => 'Passo a passo', 'lista' => [
                        'Em <b>Administração &gt; Configurações</b>, preencha os dados da empresa (razão social, CNPJ, endereço e regime tributário).',
                        'Ainda em Configurações, envie o <b>Certificado Digital (.pfx)</b> e informe a senha — ele é obrigatório para emitir NFe, NFCe e MDFe.',
                        'Cadastre as <b>Formas de Pagamento</b> que sua empresa utiliza.',
                        'Cadastre os <b>Usuários</b> da equipe e defina o perfil de acesso de cada um.',
                    ]],
                ],
                'cta_label' => 'Ir para Configurações',
                'cta_url' => route('empresa.index'),
            ],
            [
                'slug' => 'cadastrar-cliente',
                'categoria' => 'clientes',
                'titulo' => 'Como cadastrar um cliente',
                'resumo' => 'Cadastre quem vai receber suas notas e cupons.',
                'palavras_chave' => 'cliente cadastro cpf cnpj endereco destinatario',
                'blocos' => [
                    ['heading' => 'Passo a passo', 'lista' => [
                        'Acesse <b>Cliente</b> no menu e clique em <b>Novo Cliente</b>.',
                        'Informe o CPF ou CNPJ — o sistema busca automaticamente os dados cadastrais.',
                        'Complete o endereço e salve o cadastro.',
                        'Use a busca da listagem para localizar, visualizar ou editar um cliente já cadastrado.',
                    ]],
                ],
                'cta_label' => 'Ir para Clientes',
                'cta_url' => route('cliente.index'),
            ],
            [
                'slug' => 'produtos-estoque',
                'categoria' => 'produtos-estoque',
                'titulo' => 'Cadastro de produtos e controle de estoque',
                'resumo' => 'Cadastre produtos e acompanhe o que está disponível.',
                'palavras_chave' => 'produto estoque ncm cfop categoria entrada nfe importar xml disponivel sem estoque chassi',
                'blocos' => [
                    ['heading' => 'Passo a passo', 'lista' => [
                        'Em <b>Produtos &gt; Novo Produto</b>, preencha código, NCM, CFOP e os preços de custo e venda.',
                        'Organize os produtos em <b>Categorias</b> para facilitar filtros e relatórios.',
                        'Ao importar uma nota de compra em <b>Entradas NFE &gt; Importar NFe</b>, o estoque dos produtos é atualizado automaticamente.',
                        'Acompanhe os níveis em <b>Estoque</b>: os cards do topo mostram quantos produtos estão disponíveis e quantos estão sem estoque.',
                    ]],
                ],
                'cta_label' => 'Ir para Produtos',
                'cta_url' => route('produto.index'),
            ],
            [
                'slug' => 'emitir-nfe',
                'categoria' => 'nfe',
                'titulo' => 'Como emitir uma NFe',
                'resumo' => 'Nota fiscal eletrônica para vendas e remessas.',
                'palavras_chave' => 'nfe nota fiscal eletronica emitir danfe xml venda',
                'blocos' => [
                    ['heading' => 'Passo a passo', 'lista' => [
                        'Acesse <b>NFe &gt; Emitir NFe</b>.',
                        'Selecione o cliente e adicione os produtos com as quantidades vendidas.',
                        'Revise os impostos calculados e confirme a emissão.',
                        'Depois de autorizada, baixe o XML e o DANFE em <b>NFe &gt; Notas Emitidas</b> ou <b>Baixar XML</b>.',
                    ]],
                ],
                'cta_label' => 'Emitir NFe',
                'cta_url' => '/vendas/nova',
            ],
            [
                'slug' => 'emitir-nfce',
                'categoria' => 'pdv-nfce',
                'titulo' => 'Como emitir uma NFCe pelo PDV',
                'resumo' => 'Cupom fiscal para vendas de balcão.',
                'palavras_chave' => 'pdv nfce cupom fiscal balcao venda rapida',
                'blocos' => [
                    ['heading' => 'Passo a passo', 'lista' => [
                        'Acesse <b>PDV &gt; Emitir NFCe</b>.',
                        'Adicione os produtos vendidos e a forma de pagamento.',
                        'Confirme a emissão do cupom.',
                        'Consulte os cupons emitidos e baixe os XMLs em <b>PDV &gt; Notas Emitidas</b> ou <b>Baixar XML</b>.',
                    ]],
                ],
                'cta_label' => 'Emitir NFCe',
                'cta_url' => route('cupom.create'),
            ],
            [
                'slug' => 'emitir-mdfe',
                'categoria' => 'mdfe',
                'titulo' => 'Como emitir um MDFe',
                'resumo' => 'Manifesto eletrônico de documentos fiscais.',
                'palavras_chave' => 'mdfe manifesto veiculo motorista carga transporte',
                'blocos' => [
                    ['heading' => 'Passo a passo', 'lista' => [
                        'Cadastre os <b>Veículos</b> e <b>Motoristas</b> em MDFe.',
                        'Acesse <b>MDFe &gt; Emitir MDFe</b> e vincule as notas fiscais que compõem a carga.',
                        'Confirme a emissão do manifesto.',
                        'Acompanhe os manifestos emitidos e os relatórios em <b>MDFe &gt; Relatórios</b>.',
                    ]],
                ],
                'cta_label' => 'Emitir MDFe',
                'cta_url' => route('mdfe.create'),
            ],
            [
                'slug' => 'fluxo-de-caixa',
                'categoria' => 'financeiro',
                'titulo' => 'Fluxo de caixa e financeiro',
                'resumo' => 'Acompanhe entradas, saídas e faturas.',
                'palavras_chave' => 'financeiro fluxo de caixa dre fatura assinatura plano pagamento',
                'blocos' => [
                    ['heading' => 'Passo a passo', 'lista' => [
                        'Vendas de NFe e NFCe entram automaticamente no <b>Fluxo de Caixa</b>.',
                        'Lance entradas e saídas manuais quando necessário.',
                        'Consulte relatórios e o DRE em <b>Administração &gt; Fluxo de Caixa</b>.',
                        'Acompanhe a assinatura do plano e pague faturas em <b>Administração &gt; Faturas</b>.',
                    ]],
                ],
                'cta_label' => 'Ir para Fluxo de Caixa',
                'cta_url' => route('fluxo-caixa.index'),
            ],
        ];
    }

    /**
     * Um artigo por código de rejeição importado da tabela MOC 7.00.
     */
    private function artigosRejeicoesSefaz(): array
    {
        $codigos = [
            ['codigo' => '142', 'mensagem' => 'Ambiente de Contingência EPEC bloqueado para o Emitente', 'modelo' => '55/65'],
            ['codigo' => '201', 'mensagem' => 'Número máximo de numeração a inutilizar ultrapassou o limite', 'modelo' => '55/65'],
            ['codigo' => '203', 'mensagem' => 'Emissor não habilitado para emissão da NF-e', 'modelo' => '55/65'],
            ['codigo' => '204', 'mensagem' => 'Duplicidade de NF-e [nRec:999999999999999]', 'modelo' => '55/65'],
            ['codigo' => '205', 'mensagem' => 'NF-e está denegada na base de dados da SEFAZ [nRec:999999999999999]', 'modelo' => '55/65'],
            ['codigo' => '206', 'mensagem' => 'NF-e já está inutilizada na Base de Dados da SEFAZ', 'modelo' => '55/65'],
            ['codigo' => '207', 'mensagem' => 'CNPJ do emitente inválido', 'modelo' => '55/65'],
            ['codigo' => '208', 'mensagem' => 'CNPJ do destinatário inválido', 'modelo' => '55/65'],
            ['codigo' => '209', 'mensagem' => 'IE do emitente inválida', 'modelo' => '55/65'],
            ['codigo' => '210', 'mensagem' => 'IE do destinatário inválida', 'modelo' => '55/65'],
            ['codigo' => '211', 'mensagem' => 'IE do substituto inválida', 'modelo' => '55/65'],
            ['codigo' => '212', 'mensagem' => 'Data de emissão NF-e posterior a data de recebimento', 'modelo' => '55/65'],
            ['codigo' => '213', 'mensagem' => 'CNPJ-Base do Emitente difere do CNPJ-Base do Certificado Digital', 'modelo' => '55/65'],
            ['codigo' => '214', 'mensagem' => 'Tamanho da mensagem excedeu o limite estabelecido', 'modelo' => '55/65'],
            ['codigo' => '215', 'mensagem' => 'Falha no schema XML', 'modelo' => '55/65'],
            ['codigo' => '217', 'mensagem' => 'NF-e não consta na base de dados da SEFAZ', 'modelo' => '55/65'],
            ['codigo' => '218', 'mensagem' => 'NF-e já está cancelada na base de dados da SEFAZ [nRec:999999999999999]', 'modelo' => '55/65'],
            ['codigo' => '219', 'mensagem' => 'Circulação da NF-e verificada', 'modelo' => '55/65'],
            ['codigo' => '220', 'mensagem' => 'Destinatário com identificação igual à identificação do emitente', 'modelo' => '55/65'],
            ['codigo' => '221', 'mensagem' => 'Confirmado o recebimento da NF-e pelo destinatário', 'modelo' => '55/65'],
            ['codigo' => '222', 'mensagem' => 'Protocolo de Autorização de Uso difere do cadastrado', 'modelo' => '55/65'],
            ['codigo' => '223', 'mensagem' => 'CNPJ/CPF do transmissor do lote difere do CNPJ/CPF do transmissor da consulta', 'modelo' => '55/65'],
            ['codigo' => '224', 'mensagem' => 'A faixa inicial é maior que a faixa final', 'modelo' => '55/65'],
            ['codigo' => '225', 'mensagem' => 'Falha no Schema XML do lote de NFe', 'modelo' => '55/65'],
            ['codigo' => '226', 'mensagem' => 'Código da UF do Emitente diverge da UF autorizadora', 'modelo' => '55/65'],
            ['codigo' => '227', 'mensagem' => 'CPF do Emitente difere do CPF do Certificado Digital', 'modelo' => '55/65'],
            ['codigo' => '228', 'mensagem' => 'Data de Emissão muito atrasada', 'modelo' => '55/65'],
            ['codigo' => '229', 'mensagem' => 'IE do emitente não informada', 'modelo' => '55/65'],
            ['codigo' => '230', 'mensagem' => 'IE do emitente não cadastrada', 'modelo' => '55/65'],
            ['codigo' => '231', 'mensagem' => 'IE do emitente não vinculada ao CNPJ', 'modelo' => '55/65'],
            ['codigo' => '232', 'mensagem' => 'IE do destinatário não informada', 'modelo' => '55/65'],
            ['codigo' => '233', 'mensagem' => 'IE do destinatário não cadastrada', 'modelo' => '55/65'],
            ['codigo' => '234', 'mensagem' => 'IE do destinatário não vinculada ao CNPJ', 'modelo' => '55/65'],
            ['codigo' => '235', 'mensagem' => 'Inscrição SUFRAMA inválida', 'modelo' => '55/65'],
            ['codigo' => '236', 'mensagem' => 'Chave de Acesso com dígito verificador inválido', 'modelo' => '55/65'],
            ['codigo' => '237', 'mensagem' => 'CPF do destinatário inválido', 'modelo' => '55/65'],
            ['codigo' => '239', 'mensagem' => 'Versão do arquivo XML não suportada (NT 2108.004)', 'modelo' => '55/65'],
            ['codigo' => '240', 'mensagem' => 'Irregularidade Fiscal do Emitente', 'modelo' => '55/65'],
            ['codigo' => '241', 'mensagem' => 'Um número da faixa já foi utilizado', 'modelo' => '55/65'],
            ['codigo' => '243', 'mensagem' => 'XML Mal Formado', 'modelo' => '55/65'],
            ['codigo' => '244', 'mensagem' => 'Processo de Emissão pelo Contribuinte incompatível com a Série da NF', 'modelo' => '55/65'],
            ['codigo' => '245', 'mensagem' => 'CNPJ Emitente não cadastrado', 'modelo' => '55/65'],
            ['codigo' => '246', 'mensagem' => 'CNPJ Destinatário não cadastrado', 'modelo' => '55/65'],
            ['codigo' => '247', 'mensagem' => 'Sigla da UF do Emitente diverge da UF autorizadora', 'modelo' => '55/65'],
            ['codigo' => '248', 'mensagem' => 'UF do Recibo diverge da UF autorizadora', 'modelo' => '55/65'],
            ['codigo' => '249', 'mensagem' => 'UF da Chave de Acesso diverge da UF autorizadora', 'modelo' => '55/65'],
            ['codigo' => '250', 'mensagem' => 'UF diverge da UF autorizadora', 'modelo' => '55/65'],
            ['codigo' => '251', 'mensagem' => 'UF/Município destinatário não pertence a SUFRAMA', 'modelo' => '55/65'],
            ['codigo' => '252', 'mensagem' => 'Ambiente informado diverge do Ambiente de recebimento', 'modelo' => '55/65'],
            ['codigo' => '253', 'mensagem' => 'Digito Verificador da chave de acesso composta inválida', 'modelo' => '55/65'],
            ['codigo' => '254', 'mensagem' => 'NF-e complementar não possui NF referenciada', 'modelo' => '55/65'],
            ['codigo' => '255', 'mensagem' => 'NF-e complementar possui mais de uma NF referenciada', 'modelo' => '55/65'],
            ['codigo' => '256', 'mensagem' => 'Uma NF-e da faixa já está inutilizada na Base de dados da SEFAZ', 'modelo' => '55/65'],
            ['codigo' => '257', 'mensagem' => 'Solicitante não habilitado para emissão da NF-e', 'modelo' => '55/65'],
            ['codigo' => '258', 'mensagem' => 'CNPJ da consulta inválido', 'modelo' => '55/65'],
            ['codigo' => '259', 'mensagem' => 'CNPJ da consulta não cadastrado como contribuinte na UF', 'modelo' => '55/65'],
            ['codigo' => '260', 'mensagem' => 'IE da consulta inválida', 'modelo' => '55/65'],
            ['codigo' => '261', 'mensagem' => 'IE da consulta não cadastrada como contribuinte na UF', 'modelo' => '55/65'],
            ['codigo' => '262', 'mensagem' => 'UF não fornece consulta por CPF', 'modelo' => '55/65'],
            ['codigo' => '263', 'mensagem' => 'CPF da consulta inválido', 'modelo' => '55/65'],
            ['codigo' => '264', 'mensagem' => 'CPF da consulta não cadastrado como contribuinte na UF', 'modelo' => '55/65'],
            ['codigo' => '265', 'mensagem' => 'Sigla da UF da consulta difere da UF do Web Service', 'modelo' => '55/65'],
            ['codigo' => '266', 'mensagem' => 'Série utilizada não permitida no Web Service', 'modelo' => '55/65'],
            ['codigo' => '267', 'mensagem' => 'Chave de Acesso referenciada inexistente [nRef: xxx]', 'modelo' => '55/65'],
            ['codigo' => '268', 'mensagem' => 'NF Complementar referencia uma outra NF-e Complementar', 'modelo' => '55/65'],
            ['codigo' => '269', 'mensagem' => 'CNPJ/CPF Emitente da NF Complementar difere do CNPJ/CPF da NF Referenciada', 'modelo' => '55/65'],
            ['codigo' => '270', 'mensagem' => 'Código Município do Fato Gerador de ICMS inexistente', 'modelo' => '55/65'],
            ['codigo' => '271', 'mensagem' => 'Código Município do Fato Gerador: difere da UF do emitente', 'modelo' => '55/65'],
            ['codigo' => '272', 'mensagem' => 'Código Município do Emitente inexistente', 'modelo' => '55/65'],
            ['codigo' => '273', 'mensagem' => 'Código Município do Emitente: difere da UF do emitente', 'modelo' => '55/65'],
            ['codigo' => '274', 'mensagem' => 'Código Município do Destinatário inexistente', 'modelo' => '55/65'],
            ['codigo' => '275', 'mensagem' => 'Código Município do Destinatário: difere da UF do Destinatário', 'modelo' => '55/65'],
            ['codigo' => '276', 'mensagem' => 'Código Município do Local de Retirada inexistente', 'modelo' => '55/65'],
            ['codigo' => '277', 'mensagem' => 'Código Município do Local de Retirada: difere da UF do Local de Retirada', 'modelo' => '55/65'],
            ['codigo' => '278', 'mensagem' => 'Código Município do Local de Entrega inexistente', 'modelo' => '55/65'],
            ['codigo' => '279', 'mensagem' => 'Código Município do Local de Entrega: difere da UF do Local de Entrega', 'modelo' => '55/65'],
            ['codigo' => '280', 'mensagem' => 'Certificado Transmissor inválido', 'modelo' => '55/65'],
            ['codigo' => '281', 'mensagem' => 'Certificado Transmissor Data Validade', 'modelo' => '55/65'],
            ['codigo' => '282', 'mensagem' => 'Certificado Transmissor sem CNPJ/CPF', 'modelo' => '55/65'],
            ['codigo' => '283', 'mensagem' => 'Certificado Transmissor - erro Cadeia de Certificação', 'modelo' => '55/65'],
            ['codigo' => '284', 'mensagem' => 'Certificado Transmissor revogado', 'modelo' => '55/65'],
            ['codigo' => '285', 'mensagem' => 'Certificado Transmissor difere ICP-Brasil', 'modelo' => '55/65'],
            ['codigo' => '286', 'mensagem' => 'Certificado Transmissor erro no acesso a LCR', 'modelo' => '55/65'],
            ['codigo' => '287', 'mensagem' => 'Código Município do Fato Gerador de ISSQN inexistente [nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '288', 'mensagem' => 'Código Município do Fato Gerador do Transporte inexistente', 'modelo' => '55/65'],
            ['codigo' => '289', 'mensagem' => 'Código da UF informada diverge da UF solicitada', 'modelo' => '55/65'],
            ['codigo' => '290', 'mensagem' => 'Certificado Assinatura inválido', 'modelo' => '55/65'],
            ['codigo' => '291', 'mensagem' => 'Certificado Assinatura Data Validade', 'modelo' => '55/65'],
            ['codigo' => '292', 'mensagem' => 'Certificado de Assinatura sem CNPJ/CPF', 'modelo' => '55/65'],
            ['codigo' => '293', 'mensagem' => 'Certificado Assinatura - erro Cadeia de Certificação', 'modelo' => '55/65'],
            ['codigo' => '294', 'mensagem' => 'Certificado Assinatura revogado', 'modelo' => '55/65'],
            ['codigo' => '295', 'mensagem' => 'Certificado Assinatura difere ICP-Brasil', 'modelo' => '55/65'],
            ['codigo' => '296', 'mensagem' => 'Certificado Assinatura erro no acesso a LCR', 'modelo' => '55/65'],
            ['codigo' => '297', 'mensagem' => 'Assinatura difere do calculado', 'modelo' => '55/65'],
            ['codigo' => '298', 'mensagem' => 'Assinatura difere do padrão do Sistema', 'modelo' => '55/65'],
            ['codigo' => '304', 'mensagem' => 'Pedido de Cancelamento para NF-e com evento da Suframa', 'modelo' => '55/65'],
            ['codigo' => '305', 'mensagem' => 'Destinatário bloqueado na UF [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '306', 'mensagem' => 'IE do destinatário não está ativa na UF [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '315', 'mensagem' => 'Data de Emissão anterior ao início da autorização de Nota Fiscal na UF', 'modelo' => '55/65'],
            ['codigo' => '316', 'mensagem' => 'Chave de Acesso referenciada com a mesma Chave de Acesso da Nota Fiscal atual [nOcor:nnn]', 'modelo' => '55/65'],
            ['codigo' => '317', 'mensagem' => 'NF modelo 1 referenciada com data de emissão inválida [nOcor:nnn]', 'modelo' => '55/65'],
            ['codigo' => '318', 'mensagem' => 'Contranota de Produtor sem Nota Fiscal referenciada', 'modelo' => '55/65'],
            ['codigo' => '319', 'mensagem' => 'Contranota de Produtor não pode referenciar somente Nota Fiscal de entrada', 'modelo' => '55/65'],
            ['codigo' => '320', 'mensagem' => 'Contranota de Produtor referencia somente NF de outro emitente', 'modelo' => '55/65'],
            ['codigo' => '321', 'mensagem' => 'NF-e de devolução de mercadoria não possui documento fiscal referenciado', 'modelo' => '55/65'],
            ['codigo' => '322', 'mensagem' => 'NF de produtor referenciada com data de emissão inválida [nOcor:nnn]', 'modelo' => '55/65'],
            ['codigo' => '323', 'mensagem' => 'CNPJ autorizado para download inválido', 'modelo' => '55/65'],
            ['codigo' => '324', 'mensagem' => 'CNPJ do destinatário já autorizado para download', 'modelo' => '55/65'],
            ['codigo' => '325', 'mensagem' => 'CPF autorizado para download inválido', 'modelo' => '55/65'],
            ['codigo' => '326', 'mensagem' => 'CPF do destinatário já autorizado para download', 'modelo' => '55/65'],
            ['codigo' => '327', 'mensagem' => 'CFOP inválido para Nota Fiscal com finalidade de devolução de mercadoria[nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '328', 'mensagem' => 'CFOP de devolução de mercadoria para NF-e que não tem finalidade de devolução de mercadoria [nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '329', 'mensagem' => 'Número da DI /DSI inválido', 'modelo' => '55/65'],
            ['codigo' => '330', 'mensagem' => 'Informar o Valor da AFRMM na importação por via marítima', 'modelo' => '55/65'],
            ['codigo' => '331', 'mensagem' => 'Informar o CNPJ do adquirente ou do encomendante nesta forma de importação', 'modelo' => '55/65'],
            ['codigo' => '332', 'mensagem' => 'CNPJ do adquirente ou do encomendante da importação inválido', 'modelo' => '55/65'],
            ['codigo' => '333', 'mensagem' => 'Informar a UF do adquirente ou do encomendante nesta forma de importação', 'modelo' => '55/65'],
            ['codigo' => '334', 'mensagem' => 'Número do processo de drawback não informado na importação', 'modelo' => '55/65'],
            ['codigo' => '335', 'mensagem' => 'Número do processo de drawback na importação inválido', 'modelo' => '55/65'],
            ['codigo' => '336', 'mensagem' => 'Informado o grupo de exportação no item em operação que não é com exterior [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '337', 'mensagem' => 'NFC-e para emitente pessoa física', 'modelo' => '55/65'],
            ['codigo' => '338', 'mensagem' => 'Número do processo de drawback não informado na exportação', 'modelo' => '55/65'],
            ['codigo' => '339', 'mensagem' => 'Número do processo de drawback na exportação inválido', 'modelo' => '55/65'],
            ['codigo' => '340', 'mensagem' => 'Não informado o grupo de exportação indireta no item', 'modelo' => '55/65'],
            ['codigo' => '341', 'mensagem' => 'Número do registro de exportação inválido', 'modelo' => '55/65'],
            ['codigo' => '342', 'mensagem' => 'Chave de Acesso informada na Exportação Indireta com DV inválido', 'modelo' => '55/65'],
            ['codigo' => '343', 'mensagem' => 'Modelo da NF-e informada na Exportação Indireta diferente de 55', 'modelo' => '55/65'],
            ['codigo' => '344', 'mensagem' => 'Duplicidade de NF-e informada na Exportação Indireta (Chave de Acesso informada mais de uma vez)', 'modelo' => '55/65'],
            ['codigo' => '345', 'mensagem' => 'Chave de Acesso informada na Exportação Indireta não consta como NF-e referenciada', 'modelo' => '55/65'],
            ['codigo' => '346', 'mensagem' => 'Somatório das quantidades informadas na Exportação Indireta não corresponde a quantidade total do item', 'modelo' => '55/65'],
            ['codigo' => '347', 'mensagem' => 'Informada IE do substituto tributário em operação que não é interestadual', 'modelo' => '55/65'],
            ['codigo' => '348', 'mensagem' => 'NFC-e com grupo RECOPI', 'modelo' => '55/65'],
            ['codigo' => '349', 'mensagem' => 'Número RECOPI não informado', 'modelo' => '55/65'],
            ['codigo' => '350', 'mensagem' => 'Número RECOPI inválido', 'modelo' => '55/65'],
            ['codigo' => '351', 'mensagem' => 'Valor do ICMS da Operação no CST=51 difere do produto BC e Alíquota [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '352', 'mensagem' => 'Valor do ICMS Diferido no CST=51 difere do produto Valor ICMS Operação e percentual diferimento [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '353', 'mensagem' => 'Valor do ICMS no CST=51 não corresponde a diferença do ICMS operação e ICMS diferido [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '354', 'mensagem' => 'Informado grupo de devolução de tributos para NF-e que não tem finalidade de devolução de mercadoria', 'modelo' => '55/65'],
            ['codigo' => '355', 'mensagem' => 'Informar o local de saída do Pais no caso da exportação', 'modelo' => '55/65'],
            ['codigo' => '356', 'mensagem' => 'Informar o local de saída do Pais somente no caso da exportação', 'modelo' => '55/65'],
            ['codigo' => '357', 'mensagem' => 'Chave de Acesso do grupo de Exportação Indireta inexistente [nRef: xxx]', 'modelo' => '55/65'],
            ['codigo' => '358', 'mensagem' => 'Chave de Acesso do grupo de Exportação Indireta cancelada ou denegada [nRef: xxx]', 'modelo' => '55/65'],
            ['codigo' => '359', 'mensagem' => 'NF-e de venda a Órgão Público sem informar a Nota de Empenho', 'modelo' => '55/65'],
            ['codigo' => '360', 'mensagem' => 'NF-e com Nota de Empenho inválida para a UF.', 'modelo' => '55/65'],
            ['codigo' => '361', 'mensagem' => 'NF-e com Nota de Empenho inexistente na UF.', 'modelo' => '55/65'],
            ['codigo' => '362', 'mensagem' => 'Venda de combustível sem informação do Transportador', 'modelo' => '55/65'],
            ['codigo' => '363', 'mensagem' => 'IE do substituto tributário idêntica à IE do emitente ou do destinatário', 'modelo' => '55/65'],
            ['codigo' => '364', 'mensagem' => 'Total do valor da dedução do ISS difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '365', 'mensagem' => 'Total de outras retenções difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '366', 'mensagem' => 'Total do desconto incondicionado ISS difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '367', 'mensagem' => 'Total do desconto condicionado ISS difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '368', 'mensagem' => 'Total de ISS retido difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '369', 'mensagem' => 'Não informado o grupo avulsa na emissão pelo Fisco', 'modelo' => '55/65'],
            ['codigo' => '370', 'mensagem' => 'Processo de emissão pelo Fisco com Tipo de Emissão inválido', 'modelo' => '55/65'],
            ['codigo' => '372', 'mensagem' => 'Destinatário com identificação de estrangeiro com caracteres inválidos', 'modelo' => '55/65'],
            ['codigo' => '373', 'mensagem' => 'Descrição do primeiro item diferente de NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL [nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '374', 'mensagem' => 'CFOP incompatível com o grupo de tributação [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '375', 'mensagem' => 'NF-e com lançamento relativo a Cupom Fiscal referencia uma NFC-e [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '376', 'mensagem' => 'Data do Desembaraço Aduaneiro inválida [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '377', 'mensagem' => 'Código de País do destinatário inexistente', 'modelo' => '55/65'],
            ['codigo' => '378', 'mensagem' => 'Grupo de Combustível sem a informação de Encerrante [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '379', 'mensagem' => 'Grupo de Encerrante na NF-e (modelo 55) para CFOP diferente de venda de combustível para consumidor final [nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '380', 'mensagem' => 'Valor do Encerrante final não é superior ao Encerrante inicial [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '381', 'mensagem' => 'Grupo de tributação ICMS90, informando dados do ICMS-ST [nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '382', 'mensagem' => 'CFOP não permitido para o CST informado [nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '383', 'mensagem' => 'Item com CSOSN indevido [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '384', 'mensagem' => 'CSOSN não permitido para a UF [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '385', 'mensagem' => 'Grupo de tributação ICMSSN900, informando dados do ICMS-ST [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '386', 'mensagem' => 'CFOP não permitido para o CSOSN informado [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '387', 'mensagem' => 'Código de Enquadramento Legal do IPI inválido [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '388', 'mensagem' => 'Código de Situação Tributária do IPI incompatível com o Código de Enquadramento Legal do IPI [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '389', 'mensagem' => 'Código Município ISSQN inexistente [nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '390', 'mensagem' => 'Nota Fiscal com grupo de devolução de Tributos [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '391', 'mensagem' => 'Não informados os dados do cartão de crédito / débito nas Formas de Pagamento da Nota Fiscal', 'modelo' => '55/65'],
            ['codigo' => '392', 'mensagem' => 'Não informados os dados da operação de pagamento por cartão de crédito / débito', 'modelo' => '55/65'],
            ['codigo' => '393', 'mensagem' => 'NF-e com o grupo de Informações Suplementares', 'modelo' => '55/65'],
            ['codigo' => '394', 'mensagem' => 'Nota Fiscal sem a informação do QR-Code', 'modelo' => '55/65'],
            ['codigo' => '395', 'mensagem' => 'Endereço do site da UF da Consulta via QR-Code diverge do previsto', 'modelo' => '55/65'],
            ['codigo' => '396', 'mensagem' => 'Parâmetro do QR-Code inexistente: [Nome do parâmetro do QR Code: xxx)]', 'modelo' => '55/65'],
            ['codigo' => '397', 'mensagem' => 'Parâmetro do QR-Code divergente da Nota Fiscal: [Nome do parâmetro do QR Code:: xxx)]', 'modelo' => '55/65'],
            ['codigo' => '398', 'mensagem' => 'Parâmetro Versão informada no QR-Code diverge do previsto (“2”)', 'modelo' => '55/65'],
            ['codigo' => '399', 'mensagem' => 'Parâmetro de Identificação do destinatário no QR-Code para Nota Fiscal sem identificação do destinatário', 'modelo' => '55/65'],
            ['codigo' => '400', 'mensagem' => 'Parâmetro do QR-Code não está no formato hexadecimal: [Nome do parâmetro do QR Code: xxx)]', 'modelo' => '55/65'],
            ['codigo' => '401', 'mensagem' => 'CPF do emitente inválido', 'modelo' => '55/65'],
            ['codigo' => '402', 'mensagem' => 'XML da área de dados com codificação diferente de UTF-8', 'modelo' => '55/65'],
            ['codigo' => '403', 'mensagem' => 'O grupo de informações da NF-e avulsa é de uso exclusivo do Fisco', 'modelo' => '55/65'],
            ['codigo' => '404', 'mensagem' => 'Uso de prefixo de namespace não permitido', 'modelo' => '55/65'],
            ['codigo' => '407', 'mensagem' => 'CPF do Emitente somente no serviço de Nota Fiscal Avulsa no site do Fisco', 'modelo' => '55/65'],
            ['codigo' => '408', 'mensagem' => 'Evento não disponível para Autor pessoa física', 'modelo' => '55/65'],
            ['codigo' => '410', 'mensagem' => 'UF informada no campo cUF não é atendida pelo WebService (NT 2018.004)', 'modelo' => '55/65'],
            ['codigo' => '417', 'mensagem' => 'Total do ICMS superior ao valor limite estabelecido', 'modelo' => '55/65'],
            ['codigo' => '418', 'mensagem' => 'Total do ICMS ST superior ao valor limite estabelecido', 'modelo' => '55/65'],
            ['codigo' => '434', 'mensagem' => 'NF-e sem indicativo do intermediador (NT 2020.006)', 'modelo' => '55/65'],
            ['codigo' => '435', 'mensagem' => 'NF-e não pode ter o indicativo do intermediador (NT 2020.006)', 'modelo' => '55/65'],
            ['codigo' => '436', 'mensagem' => 'Informado 99-Outros como meio de pagamento (NT 2020.006)', 'modelo' => '55/65'],
            ['codigo' => '437', 'mensagem' => 'CNPJ da instituição de pagamento inválido (NT 2020.006)', 'modelo' => '55/65'],
            ['codigo' => '438', 'mensagem' => 'Obrigatória as informações do intermediador da transação para operação por site de terceiros (NT 2020.006)', 'modelo' => '55/65'],
            ['codigo' => '439', 'mensagem' => 'Informações do intermediador da transação para operação por site de terceiros preenchido indevidamente (NT 2020.006)', 'modelo' => '55/65'],
            ['codigo' => '440', 'mensagem' => 'CNPJ do intermediador da transação inválido (NT 2020.006)', 'modelo' => '55/65'],
            ['codigo' => '450', 'mensagem' => 'Modelo da NF-e diferente de 55', 'modelo' => '55/65'],
            ['codigo' => '451', 'mensagem' => 'Processo de Emissão pelo Fisco incompatível com a Série da NF', 'modelo' => '55/65'],
            ['codigo' => '453', 'mensagem' => 'Ano de inutilização não pode ser superior ao Ano atual', 'modelo' => '55/65'],
            ['codigo' => '454', 'mensagem' => 'Ano de inutilização não pode ser inferior a 2006', 'modelo' => '55/65'],
            ['codigo' => '455', 'mensagem' => 'Órgão Autor do evento diferente da UF da Chave de Acesso', 'modelo' => '55/65'],
            ['codigo' => '461', 'mensagem' => 'Informado campos de percentual de GLP e/ou GLGNn e/ou GLGNi para produto diferente de GLP [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '462', 'mensagem' => 'Código Identificador do CSC no QR-Code não cadastrado na SEFAZ', 'modelo' => '55/65'],
            ['codigo' => '463', 'mensagem' => 'Código Identificador do CSC no QR-Code foi revogado pela empresa', 'modelo' => '55/65'],
            ['codigo' => '464', 'mensagem' => 'Código de Hash no QR-Code difere do calculado', 'modelo' => '55/65'],
            ['codigo' => '465', 'mensagem' => 'Número de Controle da FCI inexistente', 'modelo' => '55/65'],
            ['codigo' => '466', 'mensagem' => 'Evento com Tipo de Autor incompatível', 'modelo' => '55/65'],
            ['codigo' => '467', 'mensagem' => 'Dados da NF-e divergentes do EPEC [tag: xxxx]', 'modelo' => '55/65'],
            ['codigo' => '468', 'mensagem' => 'NF-e com Tipo Emissão = 4, sem EPEC correspondente', 'modelo' => '55/65'],
            ['codigo' => '471', 'mensagem' => 'Informado NCM=00 indevidamente', 'modelo' => '55/65'],
            ['codigo' => '472', 'mensagem' => 'CPF consultado difere do CPF do Certificado Digital', 'modelo' => '55/65'],
            ['codigo' => '476', 'mensagem' => 'Código da UF diverge da UF da primeira NF-e do Lote', 'modelo' => '55/65'],
            ['codigo' => '477', 'mensagem' => 'Código do órgão diverge do órgão do primeiro evento do Lote', 'modelo' => '55/65'],
            ['codigo' => '478', 'mensagem' => 'Local da entrega não informado para faturamento direto de veículos novos', 'modelo' => '55/65'],
            ['codigo' => '479', 'mensagem' => 'Data de Emissão anterior a data de credenciamento ou anterior a Data de Abertura do estabelecimento', 'modelo' => '55/65'],
            ['codigo' => '480', 'mensagem' => 'Código Município do Emitente diverge do cadastrado na UF', 'modelo' => '55/65'],
            ['codigo' => '481', 'mensagem' => 'Código Regime Tributário do emitente diverge do cadastro na SEFAZ', 'modelo' => '55/65'],
            ['codigo' => '482', 'mensagem' => 'Código do Município do Destinatário diverge do cadastrado na UF', 'modelo' => '55/65'],
            ['codigo' => '483', 'mensagem' => 'Valor do desconto maior que valor do produto [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '484', 'mensagem' => 'Chave de Acesso com tipo de emissão diferente de 4 (posição 35 da Chave de Acesso)', 'modelo' => '55/65'],
            ['codigo' => '485', 'mensagem' => 'Duplicidade de numeração do EPEC (Modelo, CNPJ ou CPF, Série e Número)', 'modelo' => '55/65'],
            ['codigo' => '486', 'mensagem' => 'Não informado o Grupo de Autorização para UF que exige a identificação do Escritório de Contabilidade na Nota Fiscal', 'modelo' => '55/65'],
            ['codigo' => '487', 'mensagem' => 'Escritório de Contabilidade não cadastrado na SEFAZ', 'modelo' => '55/65'],
            ['codigo' => '488', 'mensagem' => 'Vendas do Emitente incompatíveis com o Porte da Empresa', 'modelo' => '55/65'],
            ['codigo' => '489', 'mensagem' => 'CNPJ informado inválido (DV ou zeros)', 'modelo' => '55/65'],
            ['codigo' => '489', 'mensagem' => 'CNPJ informado inválido (DV ou zeros) [nItem: 999]', 'modelo' => '55/65', 'slug' => 'rejeicao-489-2'],
            ['codigo' => '490', 'mensagem' => 'CPF informado inválido (DV ou zeros)', 'modelo' => '55/65'],
            ['codigo' => '494', 'mensagem' => 'Chave de Acesso inexistente [chNFe:99999999999999999999999999999999999999999999]', 'modelo' => '55/65'],
            ['codigo' => '495', 'mensagem' => 'CPF do Emitente com Série incompatível', 'modelo' => '55/65'],
            ['codigo' => '501', 'mensagem' => 'Prazo de cancelamento superior ao previsto na Legislação', 'modelo' => '55/65'],
            ['codigo' => '502', 'mensagem' => 'Erro na Chave de Acesso - Campo Id não corresponde à concatenação dos campos correspondentes', 'modelo' => '55/65'],
            ['codigo' => '503', 'mensagem' => 'CNPJ do emitente com Série incompatível', 'modelo' => '55/65'],
            ['codigo' => '504', 'mensagem' => 'Data de Entrada/Saída posterior ao permitido', 'modelo' => '55/65'],
            ['codigo' => '505', 'mensagem' => 'Data de Entrada/Saída anterior ao permitido', 'modelo' => '55/65'],
            ['codigo' => '506', 'mensagem' => 'Data de Saída menor que a Data de Emissão', 'modelo' => '55/65'],
            ['codigo' => '508', 'mensagem' => 'CST incompatível na operação com Não Contribuinte [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '509', 'mensagem' => 'Informado código de município diferente de “9999999” para operação com o exterior', 'modelo' => '55/65'],
            ['codigo' => '510', 'mensagem' => 'Operação com Exterior e Código País destinatário é 1058 (Brasil) ou não informado', 'modelo' => '55/65'],
            ['codigo' => '511', 'mensagem' => 'Não é de Operação com Exterior e Código País destinatário difere de 1058 (Brasil)', 'modelo' => '55/65'],
            ['codigo' => '512', 'mensagem' => 'CNPJ do Local de Retirada inválido', 'modelo' => '55/65'],
            ['codigo' => '513', 'mensagem' => 'Código Município do Local de Retirada deve ser 9999999 para UF retirada = “EX”.', 'modelo' => '55/65'],
            ['codigo' => '514', 'mensagem' => 'CNPJ do Local de Entrega inválido', 'modelo' => '55/65'],
            ['codigo' => '515', 'mensagem' => 'Código Município do Local de Entrega deve ser 9999999 para UF entrega = “EX”.', 'modelo' => '55/65'],
            ['codigo' => '516', 'mensagem' => 'Falha no schema XML – inexiste a tag raiz esperada para a mensagem', 'modelo' => '55/65'],
            ['codigo' => '517', 'mensagem' => 'Falha no schema XML – inexiste atributo versao na tag raiz da mensagem', 'modelo' => '55/65'],
            ['codigo' => '518', 'mensagem' => 'CFOP de entrada para NF-e de saída', 'modelo' => '55/65'],
            ['codigo' => '519', 'mensagem' => 'CFOP de saída para NF-e de entrada', 'modelo' => '55/65'],
            ['codigo' => '520', 'mensagem' => 'CFOP de Operação com Exterior e UF destinatário difere de “EX”', 'modelo' => '55/65'],
            ['codigo' => '521', 'mensagem' => 'Operação Interna e UF do emitente difere da UF do destinatário/remetente contribuinte do ICMS', 'modelo' => '55/65'],
            ['codigo' => '522', 'mensagem' => 'Chave de Acesso referenciada com UF inválida[nOcor:nnn]', 'modelo' => '55/65'],
            ['codigo' => '523', 'mensagem' => 'CFOP não é de Operação Estadual e UF emitente igual à UF destinatário [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '524', 'mensagem' => 'Chave de Acesso referenciada com Ano-Mês inválido [nOcor: 999]', 'modelo' => '55/65'],
            ['codigo' => '525', 'mensagem' => 'CFOP de Importação e não informado dados da DI [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '526', 'mensagem' => 'Consulta a uma Chave de Acesso muito antiga', 'modelo' => '55/65'],
            ['codigo' => '527', 'mensagem' => 'Operação de Exportação com informação de ICMS incompatível', 'modelo' => '55/65'],
            ['codigo' => '528', 'mensagem' => 'Valor do ICMS difere do produto BC e Alíquota [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '529', 'mensagem' => 'CST incompatível na operação com Contribuinte Isento de Inscrição Estadual [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '530', 'mensagem' => 'Operação com tributação de ISSQN sem informar a Inscrição Municipal', 'modelo' => '55/65'],
            ['codigo' => '531', 'mensagem' => 'Total da BC ICMS difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '532', 'mensagem' => 'Total do ICMS difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '533', 'mensagem' => 'Total da BC ICMS-ST difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '534', 'mensagem' => 'Total do ICMS-ST difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '535', 'mensagem' => 'Total do Frete difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '536', 'mensagem' => 'Total do Seguro difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '537', 'mensagem' => 'Total do Desconto difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '538', 'mensagem' => 'Total do IPI difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '539', 'mensagem' => 'Duplicidade de NF-e com diferença na Chave de Acesso [chNFe: 99999999999999999999999999999999999999999999][nRec:999999999999999]', 'modelo' => '55/65'],
            ['codigo' => '540', 'mensagem' => 'CPF do Local de Retirada inválido', 'modelo' => '55/65'],
            ['codigo' => '541', 'mensagem' => 'CPF do Local de Entrega inválido', 'modelo' => '55/65'],
            ['codigo' => '542', 'mensagem' => 'CNPJ do Transportador inválido', 'modelo' => '55/65'],
            ['codigo' => '543', 'mensagem' => 'CPF do Transportador inválido', 'modelo' => '55/65'],
            ['codigo' => '544', 'mensagem' => 'IE do Transportador inválida', 'modelo' => '55/65'],
            ['codigo' => '547', 'mensagem' => 'Chave de Acesso referenciada com Dígito Verificador inválido[nOcor:nnn]', 'modelo' => '55/65'],
            ['codigo' => '548', 'mensagem' => 'NF modelo 1 referenciada com data de emissão inválida [nOcor:nnn]', 'modelo' => '55/65'],
            ['codigo' => '549', 'mensagem' => 'CNPJ da NF referenciada de produtor inválido [nOcor: 999]', 'modelo' => '55/65'],
            ['codigo' => '550', 'mensagem' => 'CPF da NF referenciada de produtor inválido.', 'modelo' => '55/65'],
            ['codigo' => '551', 'mensagem' => 'IE da NF referenciada de produtor inválido.', 'modelo' => '55/65'],
            ['codigo' => '552', 'mensagem' => 'Chave de Acesso referenciada com CNPJ/CPF inválido[nOcor:nnn]', 'modelo' => '55/65'],
            ['codigo' => '553', 'mensagem' => 'Tipo autorizador do recibo diverge do Órgão Autorizador.', 'modelo' => '55/65'],
            ['codigo' => '554', 'mensagem' => 'IE do Emitente informada como ISENTO indevidamente', 'modelo' => '55/65'],
            ['codigo' => '556', 'mensagem' => 'Justificativa de entrada em contingência não deve ser informada para tipo de emissão normal', 'modelo' => '55/65'],
            ['codigo' => '557', 'mensagem' => 'A Justificativa de entrada em contingência deve ser informada', 'modelo' => '55/65'],
            ['codigo' => '558', 'mensagem' => 'Data de entrada em contingência posterior a data de recebimento', 'modelo' => '55/65'],
            ['codigo' => '559', 'mensagem' => 'UF do Transportador não informada', 'modelo' => '55/65'],
            ['codigo' => '560', 'mensagem' => 'CNPJ base/CPF do emitente difere do CNPJ base/CPF da primeira NF-e do lote recebido', 'modelo' => '55/65'],
            ['codigo' => '561', 'mensagem' => 'Mês de Emissão informado na Chave de Acesso difere do Mês de Emissão da NF-e', 'modelo' => '55/65'],
            ['codigo' => '562', 'mensagem' => 'Código Numérico informado na Chave de Acesso difere do Código Numérico da NF-e [chNFe:99999999999999999999999999999999999999999999', 'modelo' => '55/65'],
            ['codigo' => '563', 'mensagem' => 'Já existe pedido de Inutilização com a mesma faixa de inutilização', 'modelo' => '55/65'],
            ['codigo' => '564', 'mensagem' => 'Total do Produto / Serviço difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '565', 'mensagem' => 'Falha no schema XML – inexiste a tag raiz esperada para o lote de NF-e', 'modelo' => '55/65'],
            ['codigo' => '568', 'mensagem' => 'Falha no schema XML – inexiste atributo versao na tag raiz do lote de NF-e', 'modelo' => '55/65'],
            ['codigo' => '569', 'mensagem' => 'Data de entrada em contingência muito atrasada', 'modelo' => '55/65'],
            ['codigo' => '570', 'mensagem' => 'Tipo de Emissão 3, 6 ou 7 só é válido nas contingências SCAN/SVC', 'modelo' => '55/65'],
            ['codigo' => '571', 'mensagem' => 'Processo de emissão pelo Fisco com Certificado de Transmissão incompatível', 'modelo' => '55/65'],
            ['codigo' => '572', 'mensagem' => 'Erro Atributo ID do evento não corresponde a concatenação dos campos (“ID” + tpEvento + chNFe + nSeqEvento)', 'modelo' => '55/65'],
            ['codigo' => '573', 'mensagem' => 'Duplicidade de Evento', 'modelo' => '55/65'],
            ['codigo' => '574', 'mensagem' => 'O autor do evento diverge do emissor da NF-e', 'modelo' => '55/65'],
            ['codigo' => '575', 'mensagem' => 'O autor do evento diverge do destinatário da NF-e', 'modelo' => '55/65'],
            ['codigo' => '576', 'mensagem' => 'O autor do evento não é um órgão autorizado a gerar o evento', 'modelo' => '55/65'],
            ['codigo' => '577', 'mensagem' => 'A data do evento não pode ser menor que a data de emissão da NF-e', 'modelo' => '55/65'],
            ['codigo' => '578', 'mensagem' => 'A data do evento não pode ser maior que a data do processamento', 'modelo' => '55/65'],
            ['codigo' => '579', 'mensagem' => 'A data do evento não pode ser menor que a data de autorização para NF-e não emitida em contingência', 'modelo' => '55/65'],
            ['codigo' => '580', 'mensagem' => 'O evento exige uma NF-e autorizada', 'modelo' => '55/65'],
            ['codigo' => '587', 'mensagem' => 'Usar somente o namespace padrão da NF-e', 'modelo' => '55/65'],
            ['codigo' => '588', 'mensagem' => 'Não é permitida a presença de caracteres de edição no início/fim da mensagem ou entre as tags da mensagem', 'modelo' => '55/65'],
            ['codigo' => '589', 'mensagem' => 'Número do NSU informado superior ao maior NSU do Ambiente Nacional', 'modelo' => '55/65'],
            ['codigo' => '590', 'mensagem' => 'Informado CST para emissor do Simples Nacional (CRT=1)', 'modelo' => '55/65'],
            ['codigo' => '591', 'mensagem' => 'Informado CSOSN para emissor que não é do Simples Nacional (CRT diferente de 1)', 'modelo' => '55/65'],
            ['codigo' => '592', 'mensagem' => 'A NF-e deve ter pelo menos um item de produto sujeito ao ICMS.', 'modelo' => '55/65'],
            ['codigo' => '593', 'mensagem' => 'CNPJ-Base consultado difere do CNPJ-Base do Certificado Digital', 'modelo' => '55/65'],
            ['codigo' => '594', 'mensagem' => 'O número de sequencia do evento informado é maior que o permitido', 'modelo' => '55/65'],
            ['codigo' => '595', 'mensagem' => 'Obrigatória a informação da justificativa do evento.', 'modelo' => '55/65'],
            ['codigo' => '596', 'mensagem' => 'Evento apresentado fora do prazo: [prazo vigente]', 'modelo' => '55/65'],
            ['codigo' => '597', 'mensagem' => 'CFOP de Importação e não informado dados de IPI', 'modelo' => '55/65'],
            ['codigo' => '598', 'mensagem' => 'NF-e emitida em ambiente de homologação com Razão Social do destinatário diferente de NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL', 'modelo' => '55/65'],
            ['codigo' => '599', 'mensagem' => 'CFOP de Importação e não informado dados de II [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '600', 'mensagem' => 'CSOSN incompatível na operação com Não Contribuinte [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '601', 'mensagem' => 'Total do II difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '602', 'mensagem' => 'Total do PIS difere do somatório dos itens sujeitos ao ICMS', 'modelo' => '55/65'],
            ['codigo' => '603', 'mensagem' => 'Total da COFINS difere do somatório dos itens sujeitos ao ICMS', 'modelo' => '55/65'],
            ['codigo' => '604', 'mensagem' => 'Total do vOutro difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '605', 'mensagem' => 'Total do vServ difere do somatório do vProd dos itens sujeitos ao ISSQN', 'modelo' => '55/65'],
            ['codigo' => '606', 'mensagem' => 'Total do vBC do ISS difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '607', 'mensagem' => 'Total do ISS difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '608', 'mensagem' => 'Total do PIS difere do somatório dos itens sujeitos ao ISSQN', 'modelo' => '55/65'],
            ['codigo' => '609', 'mensagem' => 'Total da COFINS difere do somatório dos itens sujeitos ao ISSQN', 'modelo' => '55/65'],
            ['codigo' => '610', 'mensagem' => 'Total da NF difere do somatório dos Valores compõe o valor Total da NF.', 'modelo' => '55/65'],
            ['codigo' => '611', 'mensagem' => 'GTIN (cEAN) inválido [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '612', 'mensagem' => 'GTIN da unidade tributável (cEANTrib) inválido [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '613', 'mensagem' => 'Chave de Acesso difere da existente em BD', 'modelo' => '55/65'],
            ['codigo' => '614', 'mensagem' => 'Chave de Acesso inválida (Código UF inválido)', 'modelo' => '55/65'],
            ['codigo' => '615', 'mensagem' => 'Chave de Acesso inválida (Ano < 06 ou Ano maior que Ano Corrente)', 'modelo' => '55/65'],
            ['codigo' => '616', 'mensagem' => 'Chave de Acesso inválida (Mês < 1 ou Mês >  12)', 'modelo' => '55/65'],
            ['codigo' => '617', 'mensagem' => 'Chave de Acesso inválida (CNPJ/CPF zerado ou dígito inválido)', 'modelo' => '55/65'],
            ['codigo' => '618', 'mensagem' => 'Chave de Acesso inválida (modelo diferente de 55 e 65)', 'modelo' => '55/65'],
            ['codigo' => '619', 'mensagem' => 'Chave de Acesso inválida (número NF = 0)', 'modelo' => '55/65'],
            ['codigo' => '621', 'mensagem' => 'CPF Emitente não cadastrado', 'modelo' => '55/65'],
            ['codigo' => '622', 'mensagem' => 'IE emitente não vinculada ao CPF', 'modelo' => '55/65'],
            ['codigo' => '623', 'mensagem' => 'CPF Destinatário não cadastrado', 'modelo' => '55/65'],
            ['codigo' => '624', 'mensagem' => 'IE Destinatário não vinculada ao CPF', 'modelo' => '55/65'],
            ['codigo' => '625', 'mensagem' => 'Inscrição SUFRAMA deve ser informada na venda com isenção para ZFM [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '626', 'mensagem' => 'CFOP de operação isenta para ZFM diferente do previsto [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '627', 'mensagem' => 'O valor do ICMS desonerado deve ser informado [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '628', 'mensagem' => 'Total da NF superior ao valor limite estabelecido pela SEFAZ [Limite]', 'modelo' => '55/65'],
            ['codigo' => '629', 'mensagem' => 'Valor do Produto difere do produto Valor Unitário de Comercialização e Quantidade Comercial [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '630', 'mensagem' => 'Valor do Produto difere do produto Valor Unitário de Tributação e Quantidade Tributável [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '631', 'mensagem' => 'CNPJ-Base do Destinatário difere do CNPJ-Base do Certificado Digital', 'modelo' => '55/65'],
            ['codigo' => '632', 'mensagem' => 'Solicitação fora de prazo, a NF-e não está mais disponível para download', 'modelo' => '55/65'],
            ['codigo' => '633', 'mensagem' => 'NF-e indisponível para download devido a ausência de Manifestação do Destinatário', 'modelo' => '55/65'],
            ['codigo' => '634', 'mensagem' => 'Destinatário da NF-e não tem o mesmo CNPJ raiz do solicitante do download', 'modelo' => '55/65'],
            ['codigo' => '635', 'mensagem' => 'NF-e com mesmo número e série já transmitida e aguardando processamento', 'modelo' => '55/65'],
            ['codigo' => '636', 'mensagem' => 'O tipo do evento de cancelamento não corresponde ao tipo do evento a ser cancelado', 'modelo' => '55/65'],
            ['codigo' => '638', 'mensagem' => 'A quantidade de Pedidos de Prorrogação 1º prazo excede o valor limite de 20 Pedidos de Prorrogação autorizados e sem resposta do Fisco', 'modelo' => '55/65'],
            ['codigo' => '639', 'mensagem' => 'A quantidade de Pedidos de Prorrogação 2° prazo excede o valor limite de 20 Pedidos de Prorrogação autorizados e sem resposta do Fisco.', 'modelo' => '55/65'],
            ['codigo' => '640', 'mensagem' => 'CNPJ/CPF do interessado não possui permissão para consultar esta NF-e', 'modelo' => '55/65'],
            ['codigo' => '640', 'mensagem' => 'ID do Pedido de Prorrogação inválido', 'modelo' => '55/65', 'slug' => 'rejeicao-640-2'],
            ['codigo' => '641', 'mensagem' => 'A data do evento não pode ser menor que a data de autorização para o evento', 'modelo' => '55/65'],
            ['codigo' => '641', 'mensagem' => 'NF-e indisponível para o emitente', 'modelo' => '55/65', 'slug' => 'rejeicao-641-2'],
            ['codigo' => '650', 'mensagem' => 'Evento de "Ciência da Emissão" para NF-e Cancelada ou Denegada', 'modelo' => '55/65'],
            ['codigo' => '651', 'mensagem' => 'Evento de "Desconhecimento da Operação" para NF-e Cancelada ou Denegada', 'modelo' => '55/65'],
            ['codigo' => '652', 'mensagem' => 'NF-e para emitente pessoa física', 'modelo' => '55/65'],
            ['codigo' => '653', 'mensagem' => 'NF-e Cancelada, arquivo indisponível para download', 'modelo' => '55/65'],
            ['codigo' => '654', 'mensagem' => 'NF-e Denegada, arquivo indisponível para download', 'modelo' => '55/65'],
            ['codigo' => '655', 'mensagem' => 'Evento de Ciência da Emissão informado após a manifestação final do destinatário', 'modelo' => '55/65'],
            ['codigo' => '656', 'mensagem' => 'Consumo indevido pelo aplicativo da empresa [det: DESC_ERRO]', 'modelo' => '55/65'],
            ['codigo' => '657', 'mensagem' => 'Código do Órgão diverge do órgão autorizador', 'modelo' => '55/65'],
            ['codigo' => '658', 'mensagem' => 'UF do destinatário da Chave de Acesso diverge da UF autorizadora', 'modelo' => '55/65'],
            ['codigo' => '659', 'mensagem' => 'Ano-Mês da Data de Emissão diverge do Ano_Mês da Chave de Acesso', 'modelo' => '55/65'],
            ['codigo' => '660', 'mensagem' => 'CFOP de Combustível e não informado grupo de combustível da NF-e [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '661', 'mensagem' => 'NF-e já existente para o número do EPEC informado', 'modelo' => '55/65'],
            ['codigo' => '662', 'mensagem' => 'Numeração do EPEC está inutilizada na Base de Dados da SEFAZ', 'modelo' => '55/65'],
            ['codigo' => '663', 'mensagem' => 'Alíquota do ICMS com valor superior a 4 por cento na operação de saída interestadual com produtos importados [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '678', 'mensagem' => 'NF referenciada com UF diferente da NF-e complementar', 'modelo' => '55/65'],
            ['codigo' => '679', 'mensagem' => 'Chave de Acesso referenciada com Modelo inválido[nOcor:nnn]', 'modelo' => '55/65'],
            ['codigo' => '680', 'mensagem' => 'Chave de Acesso referenciada em duplicidade na NF-e [nOcor:nnn]', 'modelo' => '55/65'],
            ['codigo' => '681', 'mensagem' => 'Duplicidade de NF Modelo 1 referenciada (CNPJ, Modelo, Série e Número) [nOcor: nnn]', 'modelo' => '55/65'],
            ['codigo' => '682', 'mensagem' => 'Duplicidade de NF de Produtor referenciada (IE, Modelo, Série e Número) [nOcor: 999]', 'modelo' => '55/65'],
            ['codigo' => '683', 'mensagem' => 'Chave de Acesso referenciada com Número inválido[nOcor:nnn]', 'modelo' => '55/65'],
            ['codigo' => '684', 'mensagem' => 'Duplicidade de Cupom Fiscal referenciado (Modelo, Número de Ordem e COO) [nOcor: 999]', 'modelo' => '55/65'],
            ['codigo' => '685', 'mensagem' => 'Total do Valor Aproximado dos Tributos difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '686', 'mensagem' => 'NF Complementar referencia uma NF-e cancelada', 'modelo' => '55/65'],
            ['codigo' => '687', 'mensagem' => 'NF Complementar referencia uma NF-e denegada', 'modelo' => '55/65'],
            ['codigo' => '688', 'mensagem' => 'NF referenciada de Produtor com IE inexistente [nRef: xxx]', 'modelo' => '55/65'],
            ['codigo' => '689', 'mensagem' => 'NF referenciada de Produtor com IE não vinculada ao CNPJ/CPF informado [nRef: xxx]', 'modelo' => '55/65'],
            ['codigo' => '690', 'mensagem' => 'Pedido de Cancelamento para NF-e com CT-e ou MDF-e', 'modelo' => '55/65'],
            ['codigo' => '691', 'mensagem' => 'Chave de Acesso da NF-e diverge da Chave de Acesso do EPEC [Chave EPEC: xxxxxxxxx]', 'modelo' => '55/65'],
            ['codigo' => '692', 'mensagem' => 'Existe EPEC registrado para esta Série e Número [Chave EPEC: xxxxxxxxxxx]', 'modelo' => '55/65'],
            ['codigo' => '693', 'mensagem' => 'Alíquota de ICMS superior à definida para a operação interestadual [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '694', 'mensagem' => 'Não informado o grupo de ICMS para a UF de destino [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '695', 'mensagem' => 'Informado indevidamente o grupo de ICMS para a UF de destino [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '696', 'mensagem' => 'Operação com não contribuinte deve indicar operação com consumidor final', 'modelo' => '55/65'],
            ['codigo' => '697', 'mensagem' => 'Alíquota interestadual do ICMS com origem diferente do previsto [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '698', 'mensagem' => 'Alíquota interestadual do ICMS incompatível com as UF envolvidas na operação [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '699', 'mensagem' => 'Percentual do ICMS Interestadual para a UF de destino difere do previsto para o ano da Data de Emissão [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '701', 'mensagem' => 'Não informado Nota Fiscal referenciada (CFOP de Exportação Indireta) [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '701', 'mensagem' => 'Não informado Nota Fiscal referenciada (Lançamento relativo a Cupom Fiscal) [nItem: nnn]', 'modelo' => '55/65', 'slug' => 'rejeicao-701-2'],
            ['codigo' => '702', 'mensagem' => 'NFC-e não é aceita pela UF do Emitente', 'modelo' => '55/65'],
            ['codigo' => '703', 'mensagem' => 'Data-Hora de Emissão posterior ao horário de recebimento', 'modelo' => '55/65'],
            ['codigo' => '704', 'mensagem' => 'NFC-e com Data-Hora de emissão atrasada', 'modelo' => '55/65'],
            ['codigo' => '705', 'mensagem' => 'NFC-e com data de entrada/saída', 'modelo' => '55/65'],
            ['codigo' => '706', 'mensagem' => 'NFC-e para operação de entrada', 'modelo' => '55/65'],
            ['codigo' => '707', 'mensagem' => 'NFC-e para operação interestadual ou com o exterior', 'modelo' => '55/65'],
            ['codigo' => '708', 'mensagem' => 'NFC-e não pode referenciar documento fiscal', 'modelo' => '55/65'],
            ['codigo' => '709', 'mensagem' => 'NFC-e com formato de DANFE inválido', 'modelo' => '55/65'],
            ['codigo' => '710', 'mensagem' => 'NF-e com formato de DANFE inválido', 'modelo' => '55/65'],
            ['codigo' => '711', 'mensagem' => 'NF-e com contingência off-line', 'modelo' => '55/65'],
            ['codigo' => '712', 'mensagem' => 'NFC-e com contingência off-line para a UF', 'modelo' => '55/65'],
            ['codigo' => '713', 'mensagem' => 'Tipo de Emissão diferente de 6 ou 7 para contingência da SVC acessada', 'modelo' => '55/65'],
            ['codigo' => '714', 'mensagem' => 'NFC-e com contingência inválida (tpEmis=2, 4 (a critério da UF) ou 5)', 'modelo' => '55/65'],
            ['codigo' => '715', 'mensagem' => 'NFC-e com finalidade inválida', 'modelo' => '55/65'],
            ['codigo' => '716', 'mensagem' => 'NFC-e em operação não destinada a consumidor final', 'modelo' => '55/65'],
            ['codigo' => '717', 'mensagem' => 'NFC-e em operação não presencial', 'modelo' => '55/65'],
            ['codigo' => '718', 'mensagem' => 'NFC-e não deve informar IE de Substituto Tributário', 'modelo' => '55/65'],
            ['codigo' => '719', 'mensagem' => 'NF-e sem a identificação do destinatário', 'modelo' => '55/65'],
            ['codigo' => '720', 'mensagem' => 'Na operação com Exterior deve ser informada tag idEstrangeiro', 'modelo' => '55/65'],
            ['codigo' => '721', 'mensagem' => 'Informado idEstrangeiro e Operação não é com consumidor final.', 'modelo' => '55/65'],
            ['codigo' => '721', 'mensagem' => 'Operação interestadual deve informar CNPJ ou CPF', 'modelo' => '55/65', 'slug' => 'rejeicao-721-2'],
            ['codigo' => '722', 'mensagem' => 'CFOP de Transporte Inexistente', 'modelo' => '55/65'],
            ['codigo' => '724', 'mensagem' => 'NF-e sem o nome do destinatário', 'modelo' => '55/65'],
            ['codigo' => '725', 'mensagem' => 'NFC-e com CFOP inválido[nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '726', 'mensagem' => 'NF-e sem a informação de endereço do destinatário', 'modelo' => '55/65'],
            ['codigo' => '727', 'mensagem' => 'Operação com Exterior e UF diferente de EX', 'modelo' => '55/65'],
            ['codigo' => '728', 'mensagem' => 'NF-e sem informação da IE do destinatário', 'modelo' => '55/65'],
            ['codigo' => '729', 'mensagem' => 'NFC-e com informação da IE do destinatário', 'modelo' => '55/65'],
            ['codigo' => '730', 'mensagem' => 'NFC-e com Inscrição Suframa', 'modelo' => '55/65'],
            ['codigo' => '731', 'mensagem' => 'CFOP de operação com Exterior e idDest <> 3', 'modelo' => '55/65'],
            ['codigo' => '732', 'mensagem' => 'CFOP de operação interestadual e idDest <> 2', 'modelo' => '55/65'],
            ['codigo' => '733', 'mensagem' => 'CFOP de operação interna e idDest <> 1', 'modelo' => '55/65'],
            ['codigo' => '734', 'mensagem' => 'NFC-e com Unidade de Comercialização inválida [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '735', 'mensagem' => 'NFC-e com Unidade de Tributação inválida [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '736', 'mensagem' => 'NFC-e com grupo de Veículos novos', 'modelo' => '55/65'],
            ['codigo' => '737', 'mensagem' => 'Pagamento com cartão de crédito em sistema de automação não integrado', 'modelo' => '55/65'],
            ['codigo' => '738', 'mensagem' => 'NFC-e com grupo de Armamentos', 'modelo' => '55/65'],
            ['codigo' => '739', 'mensagem' => 'Código de País do ISSQN Inexistente', 'modelo' => '55/65'],
            ['codigo' => '740', 'mensagem' => 'Item com Repasse de ICMS retido por Substituto Tributário [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '741', 'mensagem' => 'NFC-e com Partilha de ICMS entre UF', 'modelo' => '55/65'],
            ['codigo' => '742', 'mensagem' => 'NFC-e com grupo do IPI', 'modelo' => '55/65'],
            ['codigo' => '743', 'mensagem' => 'NFC-e com grupo do II', 'modelo' => '55/65'],
            ['codigo' => '745', 'mensagem' => 'NF-e sem grupo do PIS', 'modelo' => '55/65'],
            ['codigo' => '746', 'mensagem' => 'NFC-e com grupo do PIS-ST', 'modelo' => '55/65'],
            ['codigo' => '748', 'mensagem' => 'NF-e sem grupo da COFINS', 'modelo' => '55/65'],
            ['codigo' => '749', 'mensagem' => 'NFC-e com grupo da COFINS-ST', 'modelo' => '55/65'],
            ['codigo' => '750', 'mensagem' => 'NFC-e com valor total superior ao permitido para destinatário não identificado (Código) [Limite]', 'modelo' => '55/65'],
            ['codigo' => '751', 'mensagem' => 'NFC-e com valor total superior ao permitido para destinatário não identificado (Nome) [Limite]', 'modelo' => '55/65'],
            ['codigo' => '752', 'mensagem' => 'NFC-e com valor total superior ao permitido para destinatário não identificado (Endereço) [Limite]', 'modelo' => '55/65'],
            ['codigo' => '753', 'mensagem' => 'NFC-e com Frete', 'modelo' => '55/65'],
            ['codigo' => '754', 'mensagem' => 'NFC-e com dados do Transportador', 'modelo' => '55/65'],
            ['codigo' => '755', 'mensagem' => 'NFC-e com dados de Retenção do ICMS no Transporte', 'modelo' => '55/65'],
            ['codigo' => '756', 'mensagem' => 'NFC-e com dados do veículo de Transporte', 'modelo' => '55/65'],
            ['codigo' => '757', 'mensagem' => 'NFC-e com dados de Reboque do veículo de Transporte', 'modelo' => '55/65'],
            ['codigo' => '758', 'mensagem' => 'NFC-e com dados do Vagão de Transporte', 'modelo' => '55/65'],
            ['codigo' => '759', 'mensagem' => 'NFC-e com dados da Balsa de Transporte', 'modelo' => '55/65'],
            ['codigo' => '760', 'mensagem' => 'NFC-e com dados de cobrança (Fatura, Duplicata)', 'modelo' => '55/65'],
            ['codigo' => '761', 'mensagem' => 'Código de Produto ANP inexistente [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '762', 'mensagem' => 'NFC-e com dados de compras (Empenho, Pedido, Contrato)', 'modelo' => '55/65'],
            ['codigo' => '763', 'mensagem' => 'NFC-e com dados de aquisição de Cana', 'modelo' => '55/65'],
            ['codigo' => '765', 'mensagem' => 'Lote só poderá conter NF-e ou NFC-e', 'modelo' => '55/65'],
            ['codigo' => '766', 'mensagem' => 'Item com CST indevido [nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '770', 'mensagem' => 'CFOP Inexistente [nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '771', 'mensagem' => 'Informado idEstrangeiro em operação interestadual', 'modelo' => '55/65'],
            ['codigo' => '772', 'mensagem' => 'Operação Interestadual e UF de destino igual à UF de origem', 'modelo' => '55/65'],
            ['codigo' => '773', 'mensagem' => 'Operação Interna e UF de destino difere da UF de origem', 'modelo' => '55/65'],
            ['codigo' => '774', 'mensagem' => 'NFC-e com indicador de item não participante do total [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '775', 'mensagem' => 'Modelo da NFC-e diferente de 65', 'modelo' => '55/65'],
            ['codigo' => '777', 'mensagem' => 'Obrigatória a informação do NCM completo (redação dada pela NT 2013/005 v 1.20) [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '778', 'mensagem' => 'Informado NCM inexistente[nItem:nnn]', 'modelo' => '55/65'],
            ['codigo' => '779', 'mensagem' => 'NFC-e com NCM incompatível [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '780', 'mensagem' => 'Total da NFC-e superior ao valor limite estabelecido pela SEFAZ [Limite]', 'modelo' => '55/65'],
            ['codigo' => '781', 'mensagem' => 'Emissor não habilitado para emissão da NFC-e', 'modelo' => '55/65'],
            ['codigo' => '783', 'mensagem' => 'NFC-e não é autorizada pela SVC', 'modelo' => '55/65'],
            ['codigo' => '784', 'mensagem' => 'NFC-e não permite o evento de Carta de Correção', 'modelo' => '55/65'],
            ['codigo' => '785', 'mensagem' => 'NFC-e com entrega a domicílio não permitida pela UF', 'modelo' => '55/65'],
            ['codigo' => '786', 'mensagem' => 'NFC-e de entrega a domicílio sem dados do Transportador', 'modelo' => '55/65'],
            ['codigo' => '787', 'mensagem' => 'NFC-e de entrega a domicílio sem a identificação do destinatário', 'modelo' => '55/65'],
            ['codigo' => '788', 'mensagem' => 'NFC-e de entrega a domicílio sem o endereço do destinatário', 'modelo' => '55/65'],
            ['codigo' => '789', 'mensagem' => 'NFC-e para destinatário contribuinte de ICMS', 'modelo' => '55/65'],
            ['codigo' => '790', 'mensagem' => 'Operação com Exterior para destinatário Contribuinte de ICMS', 'modelo' => '55/65'],
            ['codigo' => '791', 'mensagem' => 'NF-e com indicação de destinatário isento de IE, com a informação da IE do destinatário', 'modelo' => '55/65'],
            ['codigo' => '792', 'mensagem' => 'Informada a IE do destinatário para operação com destinatário no Exterior', 'modelo' => '55/65'],
            ['codigo' => '793', 'mensagem' => 'Valor do ICMS relativo ao Fundo de Combate à Pobreza na UF de destino difere do calculado [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '794', 'mensagem' => 'NF-e com indicativo de NFC-e com entrega a domicílio', 'modelo' => '55/65'],
            ['codigo' => '795', 'mensagem' => 'Total do ICMS desonerado difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '798', 'mensagem' => 'Valor total do ICMS relativo Fundo de Combate à Pobreza (FCP) da UF de destino difere do somatório do valor dos itens', 'modelo' => '55/65'],
            ['codigo' => '799', 'mensagem' => 'Valor total do ICMS Interestadual da UF de destino difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '800', 'mensagem' => 'Valor total do ICMS Interestadual da UF do remetente difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '805', 'mensagem' => 'A SEFAZ do destinatário não permite Contribuinte Isento de Inscrição Estadual', 'modelo' => '55/65'],
            ['codigo' => '806', 'mensagem' => 'Operação com ICMS-ST sem informação do CEST [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '807', 'mensagem' => 'NFC-e com grupo de ICMS para a UF do destinatário', 'modelo' => '55/65'],
            ['codigo' => '811', 'mensagem' => 'Pedido de Prorrogação deferido impede o cancelamento da NF-e', 'modelo' => '55/65'],
            ['codigo' => '812', 'mensagem' => 'Regime Tributário SN, com excesso de sublimite não é permitido para Emitentes desta UF', 'modelo' => '55/65'],
            ['codigo' => '813', 'mensagem' => 'QR-Code com sequência de escape para o e-comercial. Usar CDATA', 'modelo' => '55/65'],
            ['codigo' => '814', 'mensagem' => 'Nota Fiscal com grupo de comércio exterior', 'modelo' => '55/65'],
            ['codigo' => '815', 'mensagem' => 'Valor do ICMS Interestadual para UF de Destino difere do calculado [nItem: 999] (Valor Informado: XXX, Valor Calculado:XXX)', 'modelo' => '55/65'],
            ['codigo' => '816', 'mensagem' => 'Valor do ICMS Interestadual para UF do Remetente difere do calculado [nItem: 999] (Valor Informado: XXX, Valor Calculado:XXX)', 'modelo' => '55/65'],
            ['codigo' => '817', 'mensagem' => 'Unidade Tributável incompatível com o NCM informado na operação com Comércio Exterior [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '827', 'mensagem' => 'Obrigatório informar o tipo de autorização', 'modelo' => '55/65'],
            ['codigo' => '828', 'mensagem' => 'Não permitido informar o campo tipo de autorização', 'modelo' => '55/65'],
            ['codigo' => '829', 'mensagem' => 'Condição de uso não informado para o tipo de autorização de uso', 'modelo' => '55/65'],
            ['codigo' => '830', 'mensagem' => 'Não permitido preencher o campo Condição de Uso', 'modelo' => '55/65'],
            ['codigo' => '850', 'mensagem' => 'Data de vencimento da parcela não informada ou menor que a Data de vencimento da parcela anterior [nOcor: 999]', 'modelo' => '55/65'],
            ['codigo' => '851', 'mensagem' => 'Soma do valor das parcelas difere do Valor Líquido da Fatura', 'modelo' => '55/65'],
            ['codigo' => '852', 'mensagem' => 'Número da parcela inválido ou não informado [nOcor: 999]', 'modelo' => '55/65'],
            ['codigo' => '854', 'mensagem' => 'Unidade Tributável (tag:uTrib) incompatível com produto informado [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '855', 'mensagem' => 'Somatório percentuais de GLP derivado do petróleo, GLGNn e GLGNi diferente de 100 [nItem: 999].', 'modelo' => '55/65'],
            ['codigo' => '856', 'mensagem' => 'Campo valor de partida não preenchido para produto GLP [nItem: 999].', 'modelo' => '55/65'],
            ['codigo' => '857', 'mensagem' => 'Informado Duplicata Mercantil como Forma de Pagamento', 'modelo' => '55/65'],
            ['codigo' => '858', 'mensagem' => 'Grupo de Tributação informado indevidamente [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '859', 'mensagem' => 'Total do FCP retido anteriormente por Substituição Tributária difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '860', 'mensagem' => 'Valor do FCP informado difere de base de cálculo*alíquota [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '861', 'mensagem' => 'Total do FCP difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '862', 'mensagem' => 'Total do FCP ST difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '863', 'mensagem' => 'Total do IPI devolvido difere do somatório dos itens', 'modelo' => '55/65'],
            ['codigo' => '864', 'mensagem' => 'NF-e com indicativo de Operação presencial, fora do estabelecimento e não informada NF referenciada', 'modelo' => '55/65'],
            ['codigo' => '865', 'mensagem' => 'Total dos pagamentos menor que o total da nota', 'modelo' => '55/65'],
            ['codigo' => '866', 'mensagem' => 'Ausência de troco quando o valor dos pagamentos informados for maior que o total da nota', 'modelo' => '55/65'],
            ['codigo' => '868', 'mensagem' => 'Grupos Veiculo Transporte e Reboque não devem ser informados', 'modelo' => '55/65'],
            ['codigo' => '869', 'mensagem' => 'Valor do troco incorreto', 'modelo' => '55/65'],
            ['codigo' => '870', 'mensagem' => 'Data de validade incompatível com data de fabricação [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '871', 'mensagem' => 'O campo Meio de Pagamento deve ser preenchido com a opção Sem Pagamento', 'modelo' => '55/65'],
            ['codigo' => '873', 'mensagem' => 'Operação com medicamentos e não informado os campos de rastreabilidade [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '874', 'mensagem' => 'Percentual de FCP inválido [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '875', 'mensagem' => 'Percentual de FCPST inválido [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '876', 'mensagem' => 'Operação interestadual para Consumidor Final e valor do FCP informado em campo diferente de vFCPUFDest (id:NA13) [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '877', 'mensagem' => 'Data de fabricação maior que a data de processamento [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '878', 'mensagem' => 'Endereço do site da UF da Consulta por chave de acesso diverge do previsto', 'modelo' => '55/65'],
            ['codigo' => '879', 'mensagem' => 'Informado item “Produzido em Escala NÃO Relevante” e não informado CNPJ do Fabricante [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '880', 'mensagem' => 'Percentual de FCP igual a zero [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '881', 'mensagem' => 'Percentual de FCPST igual a zero [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '882', 'mensagem' => 'GTIN (cEAN) com prefixo inválido [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '883', 'mensagem' => 'GTIN (cEAN) sem informação [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '884', 'mensagem' => 'GTIN da unidade tributável (cEANTrib) com prefixo inválido [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '885', 'mensagem' => 'GTIN informado, mas não informado o GTIN da unidade tributável [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '886', 'mensagem' => 'GTIN da unidade tributável informado, mas não informado o GTIN [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '888', 'mensagem' => 'GTIN da unidade tributável (cEANTrib) sem informação [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '889', 'mensagem' => 'Obrigatória a informação do GTIN para o produto [nItem: 999]', 'modelo' => '55/65'],
            ['codigo' => '890', 'mensagem' => 'GTIN inexistente no Cadastro Centralizado de GTIN (CCG) [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '891', 'mensagem' => 'GTIN incompatível com a NCM [nItem:999; NCM esperada: 99999999]', 'modelo' => '55/65'],
            ['codigo' => '892', 'mensagem' => 'GTIN incompatível com CEST [nItem:999; CEST esperado: 9999999]', 'modelo' => '55/65'],
            ['codigo' => '893', 'mensagem' => 'GTIN da unidade tributável diverge do GTIN Contido cadastrado no CCG [nItem:999; GTIN Contido esperado: 99999999999999]', 'modelo' => '55/65'],
            ['codigo' => '894', 'mensagem' => 'GTIN da unidade tributável inexistente no Cadastro Centralizado de GTIN (CCG) [nItem:999]', 'modelo' => '55/65'],
            ['codigo' => '895', 'mensagem' => 'GTIN da unidade tributável incompatível com a NCM [nItem:999; NCM esperada: 99999999]', 'modelo' => '55/65'],
            ['codigo' => '896', 'mensagem' => 'GTIN da unidade tributável incompatível com CEST [nItem:999; CEST esperado: 9999999]', 'modelo' => '55/65'],
            ['codigo' => '899', 'mensagem' => 'Informado incorretamente o campo meio de pagamento', 'modelo' => '55/65'],
            ['codigo' => '900', 'mensagem' => 'Data de vencimento da parcela não informada ou menor que Data de Emissão [nOcor: 999]', 'modelo' => '55/65'],
            ['codigo' => '901', 'mensagem' => 'Valor do Desconto da Fatura maior que Valor Original da Fatura', 'modelo' => '55/65'],
            ['codigo' => '902', 'mensagem' => 'Valor Liquido da Fatura difere do Valor Original menos o Valor do Desconto', 'modelo' => '55/65'],
            ['codigo' => '903', 'mensagem' => 'Versão informada no QR-Code (“100”) não é mais válida para a data de emissão', 'modelo' => '55/65'],
            ['codigo' => '904', 'mensagem' => 'Informado indevidamente campo valor de pagamento', 'modelo' => '55/65'],
            ['codigo' => '905', 'mensagem' => 'Campos do grupo Fatura não informados', 'modelo' => '55/65'],
            ['codigo' => '906', 'mensagem' => 'Não informados os campos para informações do ICMS Efetivo. [nItem: nnn] [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '910', 'mensagem' => 'Chave de Acesso NF-e Substituta inválida (<nome do campo>) [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '911', 'mensagem' => 'Chave de Acesso NF-e Substituta incorreta (<nome do campo>) [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '912', 'mensagem' => 'NF-e Substituta inexistente [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '913', 'mensagem' => 'NF-e Substituta Denegada ou Cancelada [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '914', 'mensagem' => 'Data de emissão da NF-e Substituta maior que 2 horas da data de emissão da NF-e a ser cancelada [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '915', 'mensagem' => 'Valor total da NF-e Substituta difere do valor da NF-e a ser cancelada [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '916', 'mensagem' => 'Valor total do ICMS da NF-e Substituta difere do valor da NF-e a ser cancelada [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '917', 'mensagem' => 'Identificação do destinatário da NF-e Substituta difere da identificação do destinatário da NF-e a ser cancelada. [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '918', 'mensagem' => 'Quantidade de itens da NF-e Substituta difere da quantidade de itens da NF-e a ser cancelada. [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '919', 'mensagem' => 'Item da NF-e Substituta difere do mesmo item da NF-e a ser cancelada. [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '920', 'mensagem' => 'Tipo de Emissão inválido no Cancelamento por Substituição [NT 2018.004]', 'modelo' => '55/65'],
            ['codigo' => '922', 'mensagem' => 'Contranota de Produtor só pode referenciar NF-e ou NF de Produtor Modelo 4 [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '923', 'mensagem' => 'Referenciado documento de operação interna em operação interestadual ou com o exterior [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '924', 'mensagem' => 'Informado Cupom Fiscal referenciado. [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '925', 'mensagem' => 'NF-e com identificação de estrangeiro e inscrição estadual informada para destinatário [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '926', 'mensagem' => 'Operação com Exterior e país de destino igual a Brasil. [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '927', 'mensagem' => 'Número do item fora da ordem sequencial. [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '928', 'mensagem' => 'Informado código de benefício fiscal para CST sem benefício fiscal [nItem: nnn] [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '929', 'mensagem' => 'Informado CST de diferimento sem as informações de diferimento [nItem: nnn] [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '930', 'mensagem' => 'CST com benefício fiscal e não informado o código de benefício fiscal [nItem: nnn] [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '931', 'mensagem' => 'CST não corresponde ao tipo de código de benefício fiscal [nItem: nnn] [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '932', 'mensagem' => 'Informada modalidade de determinação da BC da ST como MVA e não informado o campo pMVAST [nItem: nnn] [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '933', 'mensagem' => 'Informada modalidade de determinação da BC da ST diferente de MVA e informado o campo pMVAST [nItem: nnn] [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '934', 'mensagem' => 'Não informado valor do ICMS desonerado ou o Motivo de desoneração [nItem: nnn] [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '935', 'mensagem' => 'Valor total da Base de Cálculo superior ao valor limite estabelecido [Valor Limite: R$ XXX.XXX,XX] (valor definido pela UF) [NT 2019.001]', 'modelo' => '55/65'],
            ['codigo' => '936', 'mensagem' => 'Razão Social do emitente diverge do informado no cadastro da SEFAZ', 'modelo' => '55/65'],
            ['codigo' => '938', 'mensagem' => 'Não informada BCST, pST e ICMSST retido na operação anterior [nItem: 999] [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '946', 'mensagem' => 'Informado código de benefício fiscal incorreto ou inexistente na UF [nItem: nnn]', 'modelo' => '55/65'],
            ['codigo' => '970', 'mensagem' => 'Código de País inexistente [local de retirada/entrega] [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '971', 'mensagem' => 'IE inválida [local de retirada/entrega] [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '972', 'mensagem' => 'Obrigatória as informações do responsável técnico [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '973', 'mensagem' => 'CNPJ do responsável técnico inválido [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '974', 'mensagem' => 'CNPJ do responsável técnico diverge do cadastrado  [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '975', 'mensagem' => 'Obrigatória a informação do identificador do CSRT e do Hash do CSRT [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '976', 'mensagem' => 'Identificador do CSRT não cadastrado na SEFAZ [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '977', 'mensagem' => 'Identificador do CSRT revogado [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '978', 'mensagem' => 'Hash do CSRT diverge do calculado [NT 2018.005]', 'modelo' => '55/65'],
            ['codigo' => '999', 'mensagem' => 'Erro não catalogado (informar a mensagem de erro capturado no tratamento da exceção)', 'modelo' => '55/65'],
        ];

        return array_map(function ($item) {
            $mensagem = $item['mensagem'];
            $detalhes = array_values(array_filter([
                ! empty($item['modelo']) ? '<b>Modelo:</b> '.$item['modelo'] : null,
                ! empty($item['regra']) ? '<b>Regra:</b> '.$item['regra'] : null,
                ! empty($item['grupo_xml']) ? '<b>Grupo XML:</b> '.$item['grupo_xml'] : null,
                ! empty($item['campo_xml']) ? '<b>Campo XML:</b> '.$item['campo_xml'] : null,
                ! empty($item['observacoes']) ? '<b>Observações:</b> '.$item['observacoes'] : null,
            ]));

            $blocos = [
                ['heading' => 'O que significa', 'paragrafo' => 'A SEFAZ validou o XML da NF-e/NFC-e e retornou o código '.$item['codigo'].' para indicar: <b>'.$mensagem.'</b>.'],
                ['heading' => 'Causa provável', 'paragrafo' => 'Algum dado cadastral, fiscal, tributário ou estrutural da nota não atende à regra de validação informada para essa rejeição.'],
                ['heading' => 'Como resolver', 'lista' => [
                    'Revise os dados da empresa, cliente, produtos, tributação, totais e forma de pagamento relacionados à mensagem da rejeição.',
                    'Corrija o cadastro ou os dados da nota que deram origem ao XML rejeitado.',
                    'Emita ou transmita a nota novamente após salvar a correção.',
                    'Se a mensagem envolver regra fiscal específica, confirme o enquadramento com a contabilidade ou com a SEFAZ da UF.',
                ]],
            ];

            if ($detalhes !== []) {
                $blocos[] = ['heading' => 'Detalhes técnicos', 'lista' => $detalhes];
            }

            return [
                'slug' => $item['slug'] ?? 'rejeicao-'.$item['codigo'],
                'categoria' => 'rejeicoes-sefaz',
                'titulo' => 'Rejeição '.$item['codigo'].': '.$mensagem,
                'resumo' => 'A SEFAZ rejeitou a NF-e/NFC-e porque: '.$mensagem.'.',
                'palavras_chave' => 'codigo '.$item['codigo'].' cstat rejeicao sefaz nfe nfce '.mb_strtolower($mensagem),
                'blocos' => $blocos,
                'codigo' => $item['codigo'],
            ];
        }, $codigos);
    }
}
